source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
project 'VeeContactPicker'

target 'VeeContactPicker_Example' do
    pod 'VeeContactPicker', :path => '../'
end

target 'VeeContactPicker_Tests' do
    pod 'VeeContactPicker', :path => '../'
    pod 'OCMock'
end
